### PR TITLE
Add GTFS latest of VRN

### PR DESCRIPTION
**Pull request by fnogatz**
Former URL was removed via ea586c8159b9ad7e3bad713a883c8c7a85b2bb78.

### CODE REVIEW

**Comment by hbruch** [comment]
Sorry @fnogatz for the delay, I missed the notification. https://www.vrn.de/opendata/datasets/soll-fahrplandaten-gtfs-latest returned a 404, the dataset itself was updated on Tue, 21 Jun 2022 and seems not to be updated any longer. Do you have additional information what happend to their open data offering?

**Comment by fnogatz** [comment]
No, I have no clue.

**Comment by hbruch** [comment]
The dataset has been moved to https://www.vrn.de/opendata/datasets/soll-fahrplandaten-gtfs-aktuell and requires authentication before download. Although registered, I currently receive an "invalid token" reply and can't download the feed. I sent an email to the request access.

**Comment by fnogatz** [comment]
Thank you for the update, @hbruch. The mentioned location gives me a link to https://geoportal.vrn.de/services/home/item.html?id=4ec4b1d131eb46a6bb8e216ce9b90eff, where I'm able to download the GTFS without further authentication.

**Comment by derhuerst** [comment]
This has been dealt with as of bbf254b, right?

**Comment by hbruch** [comment]
Indeed. Closing this issue as fixed.

**Pull request closed without merging**
